name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Increase patch version
      uses: maxkomarychev/patch-version@v1
      with:
        version: patch
    - name: Build with Maven
      run: mvn package
    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: target/*.jar
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: my-repository
        tags: ${{ github.event.head_commit.id }}
