name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      jar_version: ${{steps.bump.outputs.jar_version}}
 
    env:
      working-directory: ./my-app
 
    #defaults:
      #run:
        #working-directory: ${{ env.working-directory }}
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        cache-dependency-path: ./my-app
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Bump jar version
      id: bump
      run: |
        POMPATH=my-app
        OLD_VERSION=$(cd $POMPATH && mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        BUMP_MODE="none"
        old="$OLD_VERSION"
        parts=( ${old//./ } )
        bv=$((parts[2] + 1))
        NEW_VERSION="${parts[0]}.${parts[1]}.${bv}"
        echo "pom.xml at" $POMPATH "will be bumped from" $OLD_VERSION "to" $NEW_VERSION
        mvn -q versions:set -DnewVersion="${NEW_VERSION}" --file $POMPATH/pom.xml
        echo ::set-output name=jar_version::${NEW_VERSION}
    
    - name: Compile
      run: mvn -B compile --file my-app/pom.xml

    - name: Build a package
      run: mvn -B package --file my-app/pom.xml

    - name: Temporarily save jar artifact
      uses: actions/upload-artifact@v2
      with:
        name: jar-artifact
        path: ${{ github.workspace }}/my-app/target/*.jar
        retention-days: 1
    
    - name: build image
      id: build
      working-directory: ./my-app
      run: |
        docker build --build-arg VER=${{steps.bump.outputs.jar_version}} -t chernymike/cherny-maven:${{steps.bump.outputs.jar_version}} .
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
    
    - name: docker push
      run: |
        docker push chernymike/cherny-maven:${{steps.bump.outputs.jar_version}}
    - name: push to github
      run: |
        git config --global user.email ${{ secrets.GIT_EMAIL }}
        git config --global user.name ${{ secrets.GIT_USER }}
        git add ./my-app/pom.xml
        git commit -m "update version"
        git push https://${{ secrets.GIT_USER }}:${{ secrets.TOKEN }}@github.com/chernymike/maven-hello-world.git
