name: Build

on:
  push:
    branches: [ master ]

jobs:
  bump:
    runs-on: ubuntu-latest
    outputs:
      jar_version: ${{ steps.bump.outputs.jar_version }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Determine bump type
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          BUMP_TYPE="patch"
          if [[ $COMMIT_MESSAGE == *"#major"* ]]; then
            BUMP_TYPE="major"
          elif [[ $COMMIT_MESSAGE == *"#minor"* ]]; then
            BUMP_TYPE="minor"
          fi
      
      - name: Bump version
        run: |
          POMPATH=my-app
          OLD_VERSION=$(cd $POMPATH && mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          old="$OLD_VERSION"
          parts=( ${old//./ } )
          if [ "$BUMP_TYPE" == "major" ]; then
            bv=0
            parts[1]=0
            parts[2]=0
          elif [ "$BUMP_TYPE" == "minor" ]; then
            bv=0
            parts[2]=0
          else
            bv=$((parts[2] + 1))
          fi
          NEW_VERSION="${parts[0]}.${parts[1]}.${bv}"
          mvn -q versions:set -DnewVersion="${NEW_VERSION}" --file $POMPATH/pom.xml
          echo ::set-output name=jar_version::${NEW_VERSION}
          
  build:
    runs-on: ubuntu-latest
    needs: bump
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - run: cd my-app/src
    - run: mvn -B compile --file my-app/pom.xml
    - run: mvn -B package --file my-app/pom.xml
    - uses: actions/upload-artifact@v2
      with:
        name: jar-artifact
        path: my-app/target/*.jar
        retention-days: 1
        
  deploy:
    runs-on: ubuntu-18.04
    needs: bump

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
          name: jar-artifact
          path: target/
    - run: |
        docker build . -t chernymike/cherny-maven:${{needs.bump.outputs.jar_version}}
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker push
      run: |
        docker push chernymike/cherny-maven:${{needs.bump.outputs.jar_version}}
        
  run:
    runs-on: ubuntu-18.04
    needs: bump

    steps:
    - name: Run container
      run: |
        docker run chernymike/cherny-maven:${{needs.bump.outputs.jar_version}}
