name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Increase patch version
      runs: |
        # Replace "1.0.0" with the current version of your project
        current_version="1.0.0"
        # Extract patch version
        patch_version=$(echo $current_version | cut -d '.' -f 3)
        # Increment patch version
        new_patch_version=$((patch_version + 1))
        # Construct new version
        new_version=$(echo $current_version | cut -d '.' -f 1-2).$new_patch_version
        # Update pom.xml
        sed -i "s/$current_version/$new_version/g" pom.xml
    - name: Build with Maven
      run: mvn package
    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: target/*.jar
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: my-repository
        tags: ${{ github.event.head_commit.id }}
